name: coffe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg:
  font_awesome_flutter: ^8.8.1
  firebase_auth:
  google_sign_in: ^4.5.1
  provider: ^4.3.1
  string_validator: ^0.1.4
  google_fonts: ^1.1.0
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  awesome_dialog: ^1.1.3
  shared_preferences: ^0.5.8
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  flutter_spinkit: ^4.1.2
  flutter_slidable: ^0.5.5
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1

















dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/
